window.NEBULA_PRODUCTS = [
  {
    "id": "glow-stack",
    "name": "GLOW Stack",
    "formula": "BPC-157 + TB-500 + GHK-CU",
    "spec": "70MG",
    "price": 129.99,
    "category": "Recovery Stacks",
    "tag": "Best Seller",
    "accent": "#E58AC3",
    "summary": "A premium recovery research stack focused on tissue repair, flexibility, collagen support, and inflammation research.",
    "protocol": "Reconstitute with 2ml BAC Water. Common research frequency is 2-3 times per week for a 4-8 week cycle.",
    "storage": "Refrigerate at 2-8\u00b0C or freeze at -20\u00b0C. Use within 28-30 days once reconstituted."
  },
  {
    "id": "klow-stack",
    "name": "KLOW Stack",
    "formula": "BPC-157 + TB-500 + GHK-CU + KPV",
    "spec": "80MG",
    "price": 149.99,
    "category": "Recovery Stacks",
    "tag": "Gut + Recovery",
    "accent": "#EEAD70",
    "summary": "The GLOW formula upgraded with KPV for gut and inflammation research applications.",
    "protocol": "Reconstitute with 2ml BAC Water. Common research frequency is 2-3 times per week for a 4-8 week cycle.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze for long-term storage. Use within 28-30 days once reconstituted."
  },
  {
    "id": "retatrutide",
    "name": "Retatrutide",
    "formula": "GLP-1 / GIP / Glucagon Triple Agonist",
    "spec": "20MG",
    "price": 139.99,
    "category": "Metabolic Research",
    "tag": "Advanced",
    "accent": "#7E84E5",
    "summary": "A next-generation triple receptor agonist for metabolic regulation, appetite suppression, and body composition research.",
    "protocol": "Weekly subcutaneous research administration is most common. Protocols typically titrate upward over several weeks.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze up to 12 months. Use reconstituted within 21-28 days."
  },
  {
    "id": "tirzepatide",
    "name": "Tirzepatide",
    "formula": "GLP-1 / GIP Dual Agonist",
    "spec": "20MG",
    "price": 139.99,
    "category": "Metabolic Research",
    "tag": "Popular",
    "accent": "#E4ADCF",
    "summary": "A dual incretin receptor agonist with extensive research literature for metabolic effects compared with single GLP-1 compounds.",
    "protocol": "Weekly subcutaneous research administration. Studies often titrate upward over 4-8 weeks.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze for long-term storage. Use reconstituted within 21-28 days."
  },
  {
    "id": "bpc-157",
    "name": "BPC-157",
    "formula": "Tissue Repair & Gut Health",
    "spec": "10MG",
    "price": 64.99,
    "category": "Tissue Repair",
    "tag": "Entry Favorite",
    "accent": "#FFE3BA",
    "summary": "One of the most recognized recovery peptides, studied for tendon, ligament, muscle, gut, nervous system, and vascular research.",
    "protocol": "Once-daily or twice-daily research administration is common. Research cycles of 4-12 weeks are documented.",
    "storage": "Store at 2-8\u00b0C or freeze long-term. Reconstituted vials good for 28-30 days."
  },
  {
    "id": "tb-500",
    "name": "TB-500",
    "formula": "Recovery & Flexibility",
    "spec": "10MG",
    "price": 84.99,
    "category": "Tissue Repair",
    "tag": "Athletic Research",
    "accent": "#E58AC3",
    "summary": "Synthetic Thymosin Beta-4 research compound studied for systemic recovery, flexibility, endurance, inflammation, and wound healing.",
    "protocol": "Twice-weekly loading for 4-6 weeks, then once-weekly maintenance is commonly referenced in research protocols.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze long-term. Use reconstituted within 28-30 days."
  },
  {
    "id": "ipamorelin",
    "name": "Ipamorelin",
    "formula": "GH Secretagogue",
    "spec": "10MG",
    "price": 59.99,
    "category": "Growth Hormone",
    "tag": "GH Research",
    "accent": "#7E84E5",
    "summary": "Selective GH secretagogue and ghrelin mimetic studied for natural pulsatile growth hormone research patterns.",
    "protocol": "Daily research administration before sleep or fasted morning is common. Often studied with CJC-1295.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze long-term. Reconstituted vials good for 28-30 days."
  },
  {
    "id": "cjc-ipamorelin",
    "name": "CJC-1295 No DAC + Ipamorelin",
    "formula": "5MG + 5MG GH Stack",
    "spec": "10MG",
    "price": 54.99,
    "category": "Growth Hormone",
    "tag": "Most Popular GH Stack",
    "accent": "#EEAD70",
    "summary": "A widely researched GH peptide combination pairing CJC-1295 with Ipamorelin for synergistic GH pulse research.",
    "protocol": "2-3 times daily on an empty stomach is commonly referenced. Pre-sleep research timing is popular.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze long-term. Use reconstituted within 28-30 days."
  },
  {
    "id": "sermorelin",
    "name": "Sermorelin",
    "formula": "Growth Hormone Releasing Hormone",
    "spec": "10MG",
    "price": 89.99,
    "category": "Growth Hormone",
    "tag": "Classic",
    "accent": "#E4ADCF",
    "summary": "Synthetic analogue of GHRH with one of the longest research histories among GH secretagogues.",
    "protocol": "Daily subcutaneous research administration before sleep is most common. Protocols often run 3-6 months.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze long-term. Reconstituted vials good for 28-30 days."
  },
  {
    "id": "tesamorelin",
    "name": "Tesamorelin",
    "formula": "GHRH Analogue / Body Composition",
    "spec": "10MG",
    "price": 139.99,
    "category": "Growth Hormone",
    "tag": "Clinical Data",
    "accent": "#7E84E5",
    "summary": "A stabilized GHRH analogue studied specifically in body composition research, particularly visceral adipose tissue.",
    "protocol": "Daily subcutaneous research administration. Body composition studies typically run 26-52 weeks.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze up to 24 months. Use reconstituted within 21 days."
  },
  {
    "id": "epitalon",
    "name": "Epitalon",
    "formula": "Longevity & Telomere Research",
    "spec": "50MG",
    "price": 119.99,
    "category": "Longevity",
    "tag": "Longevity",
    "accent": "#FFE3BA",
    "summary": "Synthetic tetrapeptide studied for telomere extension, neuroendocrine regulation, sleep quality, antioxidant activity, and age-related biomarkers.",
    "protocol": "Cyclic research administration is typical, often 10-20 days on with extended breaks.",
    "storage": "Freeze at -20\u00b0C long-term. Refrigerate at 2-8\u00b0C short-term. Use reconstituted within 30 days."
  },
  {
    "id": "mots-c",
    "name": "MOTS-C",
    "formula": "Mitochondrial Longevity Peptide",
    "spec": "40MG",
    "price": 129.99,
    "category": "Longevity",
    "tag": "Mitochondrial",
    "accent": "#E58AC3",
    "summary": "A mitochondria-derived peptide studied for metabolism, insulin sensitivity, exercise capacity, and longevity-related pathways.",
    "protocol": "Subcutaneous research administration is most common. Weekly or several-times-weekly protocols are documented.",
    "storage": "Refrigerate at 2-8\u00b0C. Freeze long-term. Use reconstituted within 28 days."
  },
  {
    "id": "glutathione",
    "name": "Glutathione",
    "formula": "Master Antioxidant",
    "spec": "1500MG",
    "price": 54.99,
    "category": "Wellness",
    "tag": "Wellness",
    "accent": "#EEAD70",
    "summary": "The body\u2019s primary endogenous antioxidant, studied for detoxification, immune function, skin brightening, liver support, and oxidative stress research.",
    "protocol": "IV push or IM research injection is studied. Frequency ranges from daily to 2-3 times weekly.",
    "storage": "Refrigerate at 2-8\u00b0C. Sensitive to light. Use reconstituted within 14-21 days."
  },
  {
    "id": "nad",
    "name": "NAD+",
    "formula": "Cellular Energy & Longevity",
    "spec": "1000MG",
    "price": 99.99,
    "category": "Wellness",
    "tag": "Cellular Energy",
    "accent": "#7E84E5",
    "summary": "A coenzyme essential to hundreds of metabolic processes, studied for energy production, DNA repair, cognitive function, and longevity pathways.",
    "protocol": "IM or subcutaneous research injection is most common. Daily or several-times-weekly protocols are documented.",
    "storage": "Refrigerate at 2-8\u00b0C. Keep from light. Use reconstituted within 14 days."
  },
  {
    "id": "vitamin-b12",
    "name": "Vitamin B12",
    "formula": "Energy & Neurological Support",
    "spec": "10ML",
    "price": 49.99,
    "category": "Wellness",
    "tag": "Entry Level",
    "accent": "#E4ADCF",
    "summary": "Methylcobalamin injectable studied for red blood cell production, DNA synthesis, energy metabolism, cognitive function, and peripheral nerve health.",
    "protocol": "Weekly or bi-weekly IM research injection is most common. Some daily subcutaneous protocols are used.",
    "storage": "Store at room temperature or refrigerate. Keep from light. Very stable with long shelf life."
  },
  {
    "id": "bac-water",
    "name": "Bacteriostatic Water",
    "formula": "Reconstitution Solvent",
    "spec": "10ML x4",
    "price": 14.99,
    "category": "Essentials",
    "tag": "Add-On",
    "accent": "#FFE3BA",
    "summary": "Standard solvent for reconstituting lyophilized peptides. 0.9% benzyl alcohol in sterile water supports longer reconstituted stability than plain sterile water.",
    "protocol": "Use 1-2ml per peptide vial. Inject slowly down the side of the vial and gently swirl.",
    "storage": "Store at room temperature. Use within 28 days of opening. Always draw with a clean needle."
  }
];
